export default class ShopCartItemDataModel {
  prodName: string
  prodCount: number
  pic: string
  price: number
  productTotalAmount: number
  prodId: number
  skuId: number
  skuName: string
  basketId: number
  actualTotal: number
  discountId: number
  shareReduce: number
  discounts: number
  shopId: number
  shopName: string
  oriPrice: number
  distributionCardNo: number
  basketDate: string
}